version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=local_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_INITDB_ARGS=--locale=en_US.utf8
    ports:
      - "5432:5432"
