version: "3.9"

services:
  django:
    environment:
      - DJANGO_SETTINGS_MODULE=yandex_practicum_cse.production_settings
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - YDB_HOST=${YDB_HOST}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    restart: always
